package storage

import (
	"context"
	"database/sql"
	"errors"
	"time"
)

// Subscription is a long-lived opaque token that maps to one user. Clash
// fetches /sub/{token} periodically using this token; the token IS the
// credential, so it must be treated as a secret.
type Subscription struct {
	Token         string
	UserID        int64
	Name          string
	CreatedAt     time.Time
	LastFetchedAt *time.Time
	FetchCount    int64
	Revoked       bool
}

// SubscriptionRepo holds CRUD on the subscriptions table.
type SubscriptionRepo struct{ db *sql.DB }

// Insert creates a new subscription. Token must be pre-generated by the caller.
func (r *SubscriptionRepo) Insert(ctx context.Context, s *Subscription) error {
	_, err := r.db.ExecContext(ctx, `
		INSERT INTO subscriptions (token, user_id, name)
		VALUES (?, ?, ?)
	`, s.Token, s.UserID, s.Name)
	return err
}

// GetByToken loads a subscription. Returns ErrNotFound if missing. Note that
// callers must check both the Revoked flag and the user's IsDisabled flag
// before honoring the subscription.
func (r *SubscriptionRepo) GetByToken(ctx context.Context, token string) (*Subscription, error) {
	row := r.db.QueryRowContext(ctx, `
		SELECT token, user_id, name, created_at, last_fetched_at, fetch_count, revoked
		FROM subscriptions WHERE token = ?
	`, token)
	return scanSub(row)
}

// ListByUser returns the subscriptions owned by a user, newest first.
func (r *SubscriptionRepo) ListByUser(ctx context.Context, userID int64) ([]*Subscription, error) {
	rows, err := r.db.QueryContext(ctx, `
		SELECT token, user_id, name, created_at, last_fetched_at, fetch_count, revoked
		FROM subscriptions WHERE user_id = ? ORDER BY created_at DESC
	`, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []*Subscription
	for rows.Next() {
		s, err := scanSub(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, s)
	}
	return out, rows.Err()
}

// TouchFetch increments fetch_count and updates last_fetched_at. Best-effort:
// errors are non-fatal (the YAML response should still be served).
func (r *SubscriptionRepo) TouchFetch(ctx context.Context, token string) error {
	_, err := r.db.ExecContext(ctx, `
		UPDATE subscriptions
		   SET fetch_count = fetch_count + 1,
		       last_fetched_at = CURRENT_TIMESTAMP
		 WHERE token = ?
	`, token)
	return err
}

// Revoke flags a subscription as revoked. Future fetches will return 410 Gone.
func (r *SubscriptionRepo) Revoke(ctx context.Context, token string, userID int64) error {
	res, err := r.db.ExecContext(ctx, `
		UPDATE subscriptions SET revoked = 1
		WHERE token = ? AND user_id = ?
	`, token, userID)
	if err != nil {
		return err
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

func scanSub(s scanner) (*Subscription, error) {
	var sub Subscription
	var lastFetched sql.NullTime
	var revoked int
	err := s.Scan(&sub.Token, &sub.UserID, &sub.Name, &sub.CreatedAt,
		&lastFetched, &sub.FetchCount, &revoked)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	if lastFetched.Valid {
		t := lastFetched.Time
		sub.LastFetchedAt = &t
	}
	sub.Revoked = revoked != 0
	return &sub, nil
}
